import 'package:flutter_riverpod/flutter_riverpod.dart';

/// This is the [StateNotifier] for the html code of the map widget generated by the user.
class MapWidgetHTMLCode extends StateNotifier<String> {
  MapWidgetHTMLCode() : super('');

  void getCode(String code) {
    state = code;
  }
}
/// Provides the html code of the map widget generated by the user in the [InputScreen] widget.
final mapWidgetHTMLCodeProvider = StateNotifierProvider<MapWidgetHTMLCode, String>((ref) {
  return MapWidgetHTMLCode();
});