import 'package:flutter_riverpod/flutter_riverpod.dart';

// Provides the html code of the map widget generated by the user
class MapWidgetHTMLCode extends StateNotifier<String> {
  MapWidgetHTMLCode() : super('');

  void getCode(String code) {
    state = code;
  }
}
final mapWidgetHTMLCodeProvider = StateNotifierProvider<MapWidgetHTMLCode, String>((ref) {
  return MapWidgetHTMLCode();
});